src/gosura/helpers/response.clj

- profile이 없을 때 lower-case할 때 에러가 발생해서 profile이 존재할 때의 조건을 추가해줬습니다.

better conditional check for server-error fn

---

src/gosura/core.clj
src/gosura/helpers/resolver.clj
src/gosura/schema.clj

아래 인터페이스를 따르는 복수 노드 변경에 대한 resolve 지원을 추가하였습니다.
```graphql
interface Node {
id: ID!
}
interface MutationMultiPayload {
result: [Node!]!
}
type ExampleObject implements Node {
id: ID!
name: String!
}
type ExampleObjectMutationMultiPayload implements MutationMultiPayload {
result: [ExampleObject!]!
}
type DeleteSuccess {
deletedId: ID!
}
type Error {
message: String!
}
input ExampleObjectCreateMultiInput {
exampleField1: String
exampleField2: String
}
input ExampleObjectUpdateInput {
exampleField1: String
exampleField2: String
}
input ExampleObjectUpdateMultiInput {
id: ID!
set: ExampleObjectUpdateInput!
}
union ExampleObjectCreateMultiResponse = ExampleObjectMutationMultiPayload | Error
union ExampleObjectUpdateMultiResponse = ExampleObjectMutationMultiPayload | Error
type Mutation { …
```

Add resolve-update-multi

---

src/gosura/helpers/resolver.clj

- resolve-create-one 할 때 :generated-key를 resolver내에서 처리하도록 하였는데 그러다보니 한계(auth-gen 필수)가 있었음
- mutation-fn에게 id를 반환하는 역할을 넘기도록 함

take generated-key out

---

src/gosura/helpers/resolver.clj
test/gosura/helpers/resolver_test.clj

- decode-in-args 할 때 nil이 아닌 key값들만 사용하도록 변경하였습니다.

fix decode in args bug

---

src/gosura/helpers/superlifter.clj
test/gosura/helpers/superlifter_test.clj

* `gosura/superfetcher-v2` 의 사용처 중 `id-in-parent` 의 값이 `id` 가 아닌 경우 제대로 조회하지 못하는 버그가 있습니다.
* `gosura/superfetcher-v2` 에서 `batch-args` 를 내려줄 때 `id`값을 클라이언트에서 명시한 `id-in-parent` 로 변환하여 내려줍니다.

superfetcher-v2 에서 `batch-args` 내려줄 때 id 키를 id-in-parent로 rename

---

src/gosura/core.clj
src/gosura/helpers/resolver.clj
test/gosura/core_test.clj

- s/match-resolve-fn/find-resolver-fn
- resolve fn 과 resolver fn 을 섞어 사용하니, 후자로 모으려는 시도의 일부 입니다. 
- 인자 이름으로 resolver 를 받는데, clojure `keyword` 라는 사실을 강조하려고 resolver-key 로 바꿉니다.
- helpers.resolver ns 에 있는 var 를 resolver-fn 으로 부르자, docstring 에서 강조합니다. 
- 단어 `resolver-config` 를 docstring 에서 좀 더 사용합니다.

단어 resolver-fn 을 docstring 과 함수이름에 좀 더 사용합니다

---

README.md
deps.edn
src/gosura/core.clj
src/gosura/edn.clj
src/gosura/util.clj
test/gosura/edn_test.clj
test/gosura/util_test.clj
test/resources/gosura/tagged_literal_config.edn

clojure에서는 edn파일을 읽었을 때 특정 값을 함수로 사용하고 싶을 때 (var 로) qualified-symbol을 사용한 후에 requiring-resolve을 필연적으로 해줘야합니다. `#var` tagged literal을 사용해서 코드가 아닌 edn 파일에서 명시하도록 하였습니다.
클로저 코어팀에서도 이를 표준으로 넣을지 말지 고민하고 있는 것이라고 합니다. 관련 이슈 https://clojure.atlassian.net/browse/CLJ-2165
기존 코드에서는 #var가 붙어있지 않은 경우가 있어서 이를 혼용해서 사용하기 위해서 `requiring-var!`이라는 util함수를 사용해서 하위호환을 고려하였습니다.

Use #var tagged literal

---

src/gosura/core.clj
src/gosura/helpers/resolver.clj
src/gosura/helpers/resolver2.clj
src/gosura/helpers/superlifter.clj

- resolver2에 `connection-by`와 `one-by`를 추가하였습니다. 기존의 resolver에서 사용하던 `resolve-connection-by-xxx`와 
- `resolve-by-xxx`를 대체합니다.
- 공통적으로는 case변환이 중복되던 걸 제외하였습니다. (퍼포먼스 향상)
- connection-by의 경우 superfetcher 사용에 필요한 부모로부터 전달되는 필터 값을 자유롭게 조작할 수 있도록 하였습니다. (데이터화)
- one-by의 경우 superlifter 사용을 제거하였습니다. (퍼포먼스 향상)
사용해보니 큰 문제는 없고 이슈 추가해주시면 버그 수정 및 테스트 추가하겠습니다

Add experiment resolver2

---

src/gosura/helpers/resolver2.clj

- 새로 추가된 resolver2(connection-by, one-by)에서도 레코드에 키를 카멜케이스로 변환하도록 수정

resolver2 에서 record key 카멜케이스로 케이스 변환

---

README.md
deps.edn
src/gosura/helpers/db.clj
test/gosura/helpers/db_test.clj

deps.edn 에 reader macro가 사용되고 있어 인텔리제이로 프로젝트를 열었을 때 오류가 발생합니다.
https://github.com/liquidz/build.edn/blob/main/doc/deploy.adoc#environmental-variables
specter 도 제거했습니다. (굳이 쓸 이유가 없는데 의존성만 추가되기 때문)

deps.edn 파싱 오류 수정, 스펙터 제거

---

deps.edn
src/gosura/edn.clj

aero 의존성이 `#var` 를 파싱하기 위해 사용되고 있습니다.
이를 기본 edn/read + data_reader 설정으로 바꾸었습니다.

tagged literal 지원을 위해 사용되는 aero 제거

---

src/gosura/helpers/resolver2.clj

- connection-by와 one-by 시 gosura 설정 방식이 변경되었습니다.
- 가장 큰 변화는 superfetcher 정의를 생략하고, superfecther가 아닌 그냥 fetch 함수를 설정하도록 하였습니다.
변경 전
;; FetchByXXX가 defrecord로서(superlifter로서) 정의되어 있었어야함
```clojure
{:connection-by-xxx {:superfetcher #var my-ns/->FetchByxxx :parent-id {:prop :xxx :agg  :aaa}}}
```
변경 후
```clojure
{:connection-by-xxx {:fetch #var my-ns/my-fetch :parent-id {:prop :xxx :agg  :aaa}}}
```
로 사용할 수 있음.
즉, superlifter 정의를 따로 할 필요 없이 N+1 쿼리의 논리적 전개를 설정값에서 바로 할 수 있음.
그와 별개로 코드 자체가 깨끗해보이지 않는 문제가 있음. 🙏

superlifter의 정의를 gosura config에서 대신합니다

---

.gitignore
src/gosura/core.clj
src/gosura/helpers/resolver2.clj
test/gosura/core_test.clj
test/resources/gosura/sample_resolver_configs.edn

- [TOMATO-855](https://green-labs.atlassian.net/browse/TOMATO-855)
- https://github.com/green-labs/gosura/commit/df36a45eaee6ddf1fc456f72b43528d38c4947cc 에서 메모리릭 이 있었던 부분을 수정하여 generate-all 내부에서 superfetcher를 생성하도록 변경
- https://github.com/green-labs/farmmorning-clj/pull/1997 PR에서 동작 확인했습니다.
- superfetcher를 찾을 때 target-ns가 필요해서 추가로 넘겼습니다.
- one-by를 직접 호출할 때 superfetcher의 target-ns를 넘기는 것이 조금 미묘해 보이긴 합니다.

TOMATO-855 generate-all 시 superfetcher를 생성하고 one-by 호출시 생성된 superfetcher 호출하도록 변경

---

src/gosura/helpers/relay.clj
test/gosura/helpers/relay_test.clj

기존의 ID 기반 페이지네이션에 더해, 오프셋 기반 페이지네이션을 지원할 수 있도록 추가합니다.
> 참고
> 그래프QL 공식 문서에서는 커서 기반 커서를 이용함으로써 ID 기반 페이지네이션과 오프셋 기반 페이지네이션을 함께 지원할 수 있다고 명시하고 있습니다.
> https://graphql.org/learn/pagination/#pagination-and-edges

오프셋 기반 페이지네이션 지원 추가

---

src/gosura/core.clj

- 전체 filters 옵션을 각 resolver에서 사용할 수 있게 함.
- 전체 filters 옵션과 resolver 내에 filters 옵션이 겹치면 resolver filters가 덮어쓰게 함.

Filters each resolver

---

deps.edn
src/gosura/helpers/resolver2.clj
test/gosura/helpers/resolver_test.clj

기존 `resolver2/defresolver`에서 하나라도 에러가 발생하면 중간에 실행을 멈추는데, `catch-exceptions?` 설정으로 해당 부분만 `errors` 처리하고 계속해서 실행합니다. 특히 [async field resolver](https://lacinia.readthedocs.io/en/latest/resolve/async.html)를 실행할 때 에러를 적절히 처리하지 않으면 전체 쿼리 실행이 블로킹 되므로 이 옵션이 활성화되는 것을 기본 값으로 합니다.
https://lacinia.readthedocs.io/en/latest/resolve/exceptions.html

defresolver body wrapping with try catch

---

deps.edn
src/gosura/helpers/error.clj
src/gosura/helpers/resolver2.clj
test/gosura/helpers/resolver_test.clj

```json
{
"data": null,
"errors": [
{
"message": "something wrong",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"features"
],
"extensions": {
"type": "clojure.lang.ExceptionInfo",
"info": "clojure.lang.ExceptionInfo: something wrong {}",
"stacktrace": [
"farmmy.core_api.feature_flag.resolve$features$fn__76033.invoke(resolve.clj:7)",
"farmmy.core_api.feature_flag.resolve$features.invokeStatic(resolve.clj:5)",
"farmmy.core_api.feature_flag.resolve$features.invoke(resolve.clj:5)",
"com.walmartlabs.lacinia.schema$wrap_resolver_to_ensure_resolver_result$fn__25264.invoke(schema.clj:986)",
"com.walmartlabs.lacinia.executor$invoke_resolver_for_field.invokeStatic(executor.clj:86)",
"com.walmartlabs.lacinia.executor$invoke_resolver_for_field.invoke(executor.clj:68)", …
```

defresolver2 에 errors type, info 추가 및 stacktrace 원본 출력, clojure.tools.logging/error 호출

---

deps.edn
src/gosura/core.clj
src/gosura/helpers/resolver.clj
src/gosura/util.clj

deps 알고리즘은 이행적 의존성에 대해 기본적으로 newer 를 취합니다.
https://clojure.org/reference/dep_expansion#_dep_selection
따라서 라이브러리 의존성의 최신화는 보다 더 주의를 해야 하고, 보다 좋은 것은 의존성을 만들지 않는 것입니다.
그런 의미에서 아예 medley 를 없앱니다.

medley 의존성 제거

---

src/gosura/helpers/resolver2.clj

사유
- https://greenlabs-group.slack.com/archives/C02PS0G2ATB/p1673234830148629?thread_ts=1673232609.725189&cid=C02PS0G2ATB
- wrap-async-body 에서도 return-camel-case? 옵션에 따라 csk 변환을 하도록 변경합니다
- 생각하신 방향과 다르다면, 코멘트로 논의해보면 좋겠습니다!
작업
- https://github.com/green-labs/gosura/pull/90 의 브랜치 밑에 하위브랜치를 생성했습니다.
- 이 PR 병합시 https://github.com/green-labs/gosura/pull/90 로 합쳐집니다

wrap-async-body 안에서도 csk 변환

---

src/gosura/helpers/relay.clj
test/gosura/helpers/relay_test.clj
test/gosura/helpers/resolver_test.clj

뮤테이션에서 입력이 잘못된 경우 union 에러를 반환하는 것이 ADR 임에도 `decode-ids-by-keys` 중에 exception이 발생하여 `InvalidInputError`을 반환할 수 없습니다. 따라서 decode-id 에 잘못된 id 값이 들어왔을 때 `nil`을 반환하도록 변경합니다.
신선하이 코드에는 별도의 `decode-id` 구현을 사용하고 있어서 문제가 없을것 같습니다.
https://github.com/green-labs/sinsunhi-backend/blob/a31ef72386ca4d35733a45efeb5598850cdb9352/server/src/sinsun_market/graphql/relay/node.clj#L22

decode-id 에 잘못된 id 값이 들어왔을 때 nil을 반환

---

API.md
README.md
deps.edn
src/gosura/core.clj
src/gosura/helpers/case_format.clj
src/gosura/helpers/db.clj
src/gosura/helpers/resolver.clj
src/gosura/helpers/resolver2.clj
src/gosura/util.clj
test/gosura/core_test.clj
test/gosura/helpers/resolver_test.clj

> * `camel-snake-kebab` 케이스 변환은 매우 빈번하게 호출되며, APM에서 확인했을 때 CPU 사용률 비중 높음
> * `UserPostsFeedQuery` 쿼리 기준 case 변환이 1070회 호출, 이는 필드 resolver 들에 대해 case 변환이 중복으로 일어나고 있기 때문.
> * 케이스 변환을 최소화 하기 위해 [graphql 인자와 필드 케이싱 효율화 #2384](https://github.com/green-labs/farmmorning-clj/issues/2384) 를 적용했으나 아래의 문제가 있음.
> 
> 1. 하위 호환성 유지를 위해 `return-camel-case?` 의 기본설정은 여전히 true이고,  false 사용을 각 개발자에게 맡김.
> 2. 절대 다수의 resolver에서 여전히 비효율적인 형변환이 실행되고 있음.
> 
> 이를 해결하기 위해 다음을 실시할 예정입니다.
> 
> * `return-camel-case?` 및 `parent`의 `kebab-case?` 설정을 처리하는 로직을 defresolver, gosura, resolver-helper에서 없앤다. (있던 없던 상관없는 옵셔널 필드로 만듦)
> * default-field-resolver 에서 kebab, camel, + 예외(guava를 통해 kebab-case를 처리했을 때) 경우를 핸들링 할 수 있도록 한다.
> * default-field-resolver 에 대한 테스트를 추가하고, regression 테스트를 진행한다.
> 
> 이렇게 되면 csk 라이브러리가 호출되는 횟수를 …

return-camel-case? 및 parent kebab-case? 케이스 변환 제거

---

src/gosura/schema.clj
test/gosura/helpers/relay_test.clj

global node id 생성시에 :db-id가 int? 인지 검사하고 있다.
int? 는 타입 검사라서 int 타입이 아니면 거짓으로 판정한다.
MySQL DB에서 id 칼럼의 타입을 BIGINT로 설정한 경우 클로저에서는
java.math.BigInteger 타입으로 입력된다.
그래서 int? 검사에 실패하게 된다.
int? 를 논리적 정수 검사 함수인 integer? 로 변경한다.

BIGINT db-id 지원
