green-labs/gosura

.github/release.yml
=> release github actions

.github/workflows/release.yml
#3 에서 디폴트로 항상 patch version up을 하고자 합니다.
=> minor -> patch

.github/workflows/release.yml
#3 에서
norelease 를 디폴트로 해서 release version up을 하지 않고
태그를 사용해서 `release:patch/minor/major` 이를 버전을 업데이트하고자 합니다.
=> norelease for bump version

src/gosura/helpers/resolver.clj
=> bad require ns

src/gosura/core.clj
=> fix bad require

deps.edn
=> #25 remove unused deps

.gitignore, src/gosura/core.clj, src/gosura/helpers/resolver.clj, src/gosura/schema.clj
- 단일 Node resolve하는 resolver를 추가했습니다.
=> Add Resolve one

src/gosura/core.clj
- add missing requiring-resolve `fetch-one` symbol
=> requiring-resolve fetch-one

src/gosura/helpers/resolver.clj
- common-pre-process-arguments에 -id로 끝나는 것도 디코딩 처리하도록, 키워드 값을 staging으로 변환하는 로직 추가
=> fix common-pre-process

src/gosura/core.clj, src/gosura/helpers/resolver.clj, src/gosura/helpers/superlifter.clj
- Add error log on failed response.
- minor sort namespaces
=> Add error log

.clj-kondo/config.edn, src/gosura/auth.clj, src/gosura/helpers/resolver.clj, src/gosura/helpers/resolver2.clj, src/gosura/util.clj, test/gosura/helpers/resolver_test.clj
이슈: #50 
defresolver에서 filter/auth를 추가하였습니다.
=> defresolver2

src/gosura/schema.clj, test/gosura/auth_test.clj, test/gosura/core_test.clj, test/resources/gosura/sample_resolver_configs.edn
malli 스키마에서 symbol?로 체크하던 로직을 var?여도 valid schema가 되도록 수정하였습니다
=> Fix config schema to use var tag

src/gosura/helpers/relay.clj, src/gosura/helpers/resolver2.clj, test/gosura/helpers/relay_test.clj, test/gosura/helpers/resolver_test.clj
- decode-ids-by-keys 옵션 추가
- auth가 없으면 인증되지 않았다고 뜨는 minor bug 수정
=> Add decode id keys options

API.md, README.md, deps.edn
- https://github.com/borkdude/quickdoc 를 이용하여 API 문서를 만들었습니다.
https://github.com/green-labs/gosura/blob/api-doc/API.md
^ 요거입니다.
=> API doc using quickdoc

README.md
이삭을 줍고 싶었으나 gosura 는 이삭줍기 대상이 아니군요.. 😭
=> 오타 수정 quary -> query

deps.edn, src/gosura/helpers/db.clj
trace 를 추가하여 fetch 함수 실행 시 trace가 실행되도록 하였습니다.
이는 프로덕션 환경에(compile-enabled false) 지장이 없습니다.
=> Add trace for investigating sql

src/gosura/helpers/resolver2.clj
=> Fix threading macro bug

src/gosura/helpers/resolver2.clj
Reverts green-labs/gosura#73
이유
- 데이터베이스 호출 문제 체크
- 메모리 leak
=> Revert "superlifter의 정의를 gosura config에서 대신합니다"

src/gosura/helpers/relay.clj
가독성 개선을 위한 이름 수정입니다.
구현, 인터페이스에 영향이 없습니다.
=> build-page-options 의 limit, page-size 로컬 이름 수정

.gitignore, src/gosura/core.clj, src/gosura/helpers/resolver2.clj, test/gosura/core_test.clj, test/resources/gosura/sample_resolver_configs.edn
=> Revert "TOMATO-855 generate-all 시 superfetcher를 생성하고 one-by 호출시 생성된 superfetcher 호출하도록 변경"

deps.edn, src/gosura/helpers/resolver2.clj
v2/defresolver taoensso.timbre 로 에러 로그 변경
=> taoensso.timbre 로 에러 로그 변경

test/gosura/helpers/relay_test.clj
=> decode-id-test 수정

src/gosura/core.clj, src/gosura/helpers/resolver.clj, src/gosura/helpers/resolver2.clj, src/gosura/schema.clj
```clojure
{:target-ns          farmmorning.graphql.resolver.community.subject
:node-type          :community-subject
:db-key             :db
:return-camel-case? false
:resolvers          {:resolve-node       {:table-fetcher #var farmmorning.community.interface.subject/fetch
:return-camel-case? true}
:resolve-connection {:table-fetcher #var farmmorning.community.interface.subject/fetch-available-only
:settings {:return-camel-case? true}}}}
```
위 처럼 `return-camel-case?` 를 끄고 켤수 있습니다.
=> 모든 생성 함수에 return-camel-case? 옵션 추가
